
import type { Work } from '../types';

export const works: Work[] = [
  {
    id: 'neon-drifter',
    title: 'Neon Drifter',
    category: 'Original TV Series',
    year: '2024',
    role: 'Studio · Direction · VFX',
    description:
      'A 12-episode cyberpunk road saga rendered with hand-painted light leaks and generative cityscapes that breathe with the score.',
    theme: '#ff476f',
    tagline: 'The road is the only law left.',
    format: '12 Episodes · 24 min',
    duration: '2:14',
    liveDemo: 'https://kaze.studio/neon-drifter',
    github: 'https://github.com/kaze-studio/neon-drifter',
    techStack: [
      { name: 'TVPaint', role: 'Frame-by-frame character animation' },
      { name: 'Houdini', role: 'Procedural city & traffic simulation' },
      { name: 'After Effects', role: 'Compositing & light leaks' },
      { name: 'DaVinci Resolve', role: 'Grade & finishing' },
      { name: 'Custom GLSL', role: 'Neon bloom & rain shaders' },
    ],
    animationTechniques: [
      { name: 'Light Leak Painting', note: 'Every frame hand-painted with volumetric glow passes.' },
      { name: 'Generative Cities', note: 'Procedural skylines that rebuild per episode.' },
      { name: 'Rain Slash FX', note: 'Simulated streaks comped over 2D holds.' },
      { name: 'Audioreactive Cuts', note: 'Edits locked to a 140 BPM synth score.' },
      { name: 'Anime Slash Wipes', note: 'GSAP-driven skewed panel transitions.' },
    ],
    metrics: [
      { value: 12, label: 'Episodes Shipped' },
      { value: 62, suffix: 'M', label: 'Frames Animated' },
      { value: 9, label: 'Awards Nominated' },
      { value: 4.9, suffix: '/5', label: 'Fan Rating' },
    ],
    timeline: [
      { phase: 'Concept & Pilot', duration: 'Mar – May 2023', desc: 'Mood bible, 3-minute pilot, key art.' },
      { phase: 'Visual Dev', duration: 'Jun – Sep 2023', desc: 'Characters, city engine, color script.' },
      { phase: 'Production', duration: 'Oct 2023 – Jun 2024', desc: 'Animation, VFX, and comp across 12 episodes.' },
      { phase: 'Finishing', duration: 'Jul – Aug 2024', desc: 'Grade, sound, and festival masters.' },
    ],
    challenge:
      'Rendering a living cyberpunk metropolis for 12 episodes without drowning the team in repetitive background work.',
    solution:
      'We built a procedural city engine in Houdini and painted light leaks by hand only on hero frames, balancing scale with soul.',
    beforeCaption: 'Static grey layout',
    afterCaption: 'Neon living city',
    gallery: [
      { id: 'nd-1', variant: 0, caption: 'Opening highway sweep' },
      { id: 'nd-2', variant: 1, caption: 'Rooftop standoff' },
      { id: 'nd-3', variant: 2, caption: 'Rain market' },
      { id: 'nd-4', variant: 3, caption: 'Core memory' },
      { id: 'nd-5', variant: 1, caption: 'Drifter silhouette' },
      { id: 'nd-6', variant: 2, caption: 'End card' },
    ],
    prototype: { type: 'color', hint: 'Shift the city mood and run the intro sweep.' },
  },
  {
    id: 'crimson-lotus',
    title: 'Crimson Lotus',
    category: 'Feature Film',
    year: '2023',
    role: 'Animation Lead',
    description:
      'A period fantasy feature told through ink-wash transitions and frame-by-frame combat choreography rooted in kabuki rhythm.',
    theme: '#f9c74f',
    tagline: 'A blade remembered is a blade unbroken.',
    format: 'Feature · 98 min',
    duration: '1:48',
    liveDemo: 'https://kaze.studio/crimson-lotus',
    github: 'https://github.com/kaze-studio/crimson-lotus',
    techStack: [
      { name: 'Toonz', role: 'Ink & paint pipeline' },
      { name: 'Blender', role: 'Layout & camera' },
      { name: 'Nuke', role: 'Ink-wash compositing' },
      { name: 'Storyboard Pro', role: 'Action previs' },
    ],
    animationTechniques: [
      { name: 'Ink-Wash Transition', note: 'Bleeding strokes between scenes.' },
      { name: 'Kabuki Timing', note: 'Pauses and snaps drawn from theatre.' },
      { name: 'Frame Combat', note: 'Hand-led sword choreography.' },
      { name: 'Puppet Smear', note: 'Motion blur as painted arcs.' },
    ],
    metrics: [
      { value: 98, suffix: 'min', label: 'Runtime' },
      { value: 41, suffix: 'M', label: 'Frames' },
      { value: 3, label: 'Festival Wins' },
      { value: 1, label: 'Theatrical Run' },
    ],
    timeline: [
      { phase: 'Script & Boards', duration: 'Jan – Apr 2022', desc: 'Beat board and action previs.' },
      { phase: 'Design', duration: 'May – Aug 2022', desc: 'Costumes, ink palette, sets.' },
      { phase: 'Animation', duration: 'Sep 2022 – Apr 2023', desc: 'Combat and dialogue passes.' },
      { phase: 'Composite', duration: 'May – Jul 2023', desc: 'Ink-wash finish.' },
    ],
    challenge:
      'Honoring classical ink painting while keeping 98 minutes of combat readable and fast.',
    solution:
      'We choreographed to kabuki rhythm and replaced digital blur with painted smear arcs, keeping every hit tactile.',
    beforeCaption: 'Flat digital color',
    afterCaption: 'Ink-wash finish',
    gallery: [
      { id: 'cl-1', variant: 1, caption: 'Lotus duel' },
      { id: 'cl-2', variant: 2, caption: 'Temple court' },
      { id: 'cl-3', variant: 3, caption: 'Blood moon' },
      { id: 'cl-4', variant: 0, caption: 'Training montage' },
      { id: 'cl-5', variant: 2, caption: 'Final stance' },
      { id: 'cl-6', variant: 0, caption: 'Title card' },
    ],
    prototype: { type: 'character', hint: 'Parallax the duel and sweep the ink reveal.' },
  },
  {
    id: 'echoes-of-tomorrow',
    title: 'Echoes of Tomorrow',
    category: 'Music Video',
    year: '2023',
    role: 'Studio · Design',
    description:
      'A 4-minute audioreactive piece syncing particle motion to a live-recorded synth score, built entirely in code.',
    theme: '#4cc9f0',
    tagline: 'Sound made visible.',
    format: 'Music Video · 4 min',
    duration: '0:58',
    liveDemo: 'https://kaze.studio/echoes',
    github: 'https://github.com/kaze-studio/echoes',
    techStack: [
      { name: 'WebGL', role: 'GPU particle system' },
      { name: 'Tone.js', role: 'Audio analysis' },
      { name: 'GSAP', role: 'Timeline & text' },
      { name: 'Ableton', role: 'Source score' },
    ],
    animationTechniques: [
      { name: 'Audioreactive Particles', note: 'Frequency drives emission.' },
      { name: 'Beat Synced Cuts', note: 'Edits locked to transients.' },
      { name: 'Type as Light', note: 'Lyrics rendered as glow.' },
      { name: 'Flow Fields', note: 'Curl-noise motion paths.' },
    ],
    metrics: [
      { value: 4, suffix: 'min', label: 'Runtime' },
      { value: 8, suffix: 'M', label: 'Particles / sec' },
      { value: 12, suffix: 'M', label: 'Views' },
      { value: 2, label: 'VFX Awards' },
    ],
    timeline: [
      { phase: 'Score Lock', duration: 'Feb 2023', desc: 'Live synth recording.' },
      { phase: 'System Build', duration: 'Mar 2023', desc: 'WebGL particle core.' },
      { phase: 'Edit', duration: 'Apr 2023', desc: 'Audioreactive cut.' },
      { phase: 'Release', duration: 'May 2023', desc: 'Festival & online drop.' },
    ],
    challenge:
      'Making a code-driven video feel as emotional as hand-drawn work.',
    solution:
      'We mapped the score’s dynamics to a curl-noise flow field so the particles breathe with the music instead of just reacting.',
    beforeCaption: 'Static frames',
    afterCaption: 'Living frequency',
    gallery: [
      { id: 'et-1', variant: 3, caption: 'Intro burst' },
      { id: 'et-2', variant: 0, caption: 'Chorus wave' },
      { id: 'et-3', variant: 1, caption: 'Bridge calm' },
      { id: 'et-4', variant: 2, caption: 'Drop' },
      { id: 'et-5', variant: 3, caption: 'Outro fade' },
      { id: 'et-6', variant: 0, caption: 'Poster' },
    ],
    prototype: { type: 'parallax', hint: 'Drive the particle field with your cursor.' },
  },
  {
    id: 'silent-horizon',
    title: 'Silent Horizon',
    category: 'Short Film',
    year: '2022',
    role: 'Direction · Art',
    description:
      'A wordless meditation on isolation, built from long holds, minimal palette, and tidal motion.',
    theme: '#80ed99',
    tagline: 'Stillness speaks loudest.',
    format: 'Short · 7 min',
    duration: '1:02',
    liveDemo: 'https://kaze.studio/silent-horizon',
    github: 'https://github.com/kaze-studio/silent-horizon',
    techStack: [
      { name: 'TVPaint', role: 'Long-hold animation' },
      { name: 'Procreate', role: 'Mato-like backgrounds' },
      { name: 'Premiere', role: 'Editorial' },
    ],
    animationTechniques: [
      { name: 'Held Frames', note: 'Seconds of stillness for weight.' },
      { name: 'Tidal Loop', note: 'Seamless ocean cycles.' },
      { name: 'Minimal Palette', note: 'Four tones only.' },
      { name: 'Breath Scale', note: 'Subtle zoom on inhale.' },
    ],
    metrics: [
      { value: 7, suffix: 'min', label: 'Runtime' },
      { value: 4, label: 'Colors Used' },
      { value: 14, label: 'Festivals' },
      { value: 1, label: 'Jury Prize' },
    ],
    timeline: [
      { phase: 'Idea', duration: 'Jun 2021', desc: 'One-line premise.' },
      { phase: 'Art', duration: 'Jul – Sep 2021', desc: 'Four-tone palette.' },
      { phase: 'Animate', duration: 'Oct – Dec 2021', desc: 'Holds & tides.' },
      { phase: 'Cut', duration: 'Jan 2022', desc: 'Silent editorial.' },
    ],
    challenge:
      'Telling a story with zero dialogue and almost no motion.',
    solution:
      'We leaned on held frames and a single looping tide, letting negative space carry the emotion.',
    beforeCaption: 'Busy frame',
    afterCaption: 'Quiet horizon',
    gallery: [
      { id: 'sh-1', variant: 2, caption: 'Dawn hold' },
      { id: 'sh-2', variant: 0, caption: 'Lone figure' },
      { id: 'sh-3', variant: 3, caption: 'Tide turn' },
      { id: 'sh-4', variant: 1, caption: 'Horizon line' },
      { id: 'sh-5', variant: 2, caption: 'Closing' },
      { id: 'sh-6', variant: 0, caption: 'Poster' },
    ],
    prototype: { type: 'color', hint: 'Drag the time-of-day slider across the quiet shore.' },
  },
  {
    id: 'paper-moons',
    title: 'Paper Moons',
    category: 'Original OVA',
    year: '2022',
    role: 'Studio',
    description:
      'A tender coming-of-age story wrapped in cut-paper textures and stop-motion-inspired timing.',
    theme: '#b5179e',
    tagline: 'Folded from small hopes.',
    format: 'OVA · 45 min',
    duration: '1:36',
    liveDemo: 'https://kaze.studio/paper-moons',
    github: 'https://github.com/kaze-studio/paper-moons',
    techStack: [
      { name: 'Photoshop', role: 'Cut-paper textures' },
      { name: 'Dragonframe', role: 'Stop-motion timing ref' },
      { name: 'After Effects', role: '2.5D layers' },
    ],
    animationTechniques: [
      { name: 'Cut-Paper Layers', note: 'Parallax paper depth.' },
      { name: 'Stop-Motion Timing', note: 'Deliberate, chunky keys.' },
      { name: 'Paper Curl', note: 'Edge warps on turns.' },
      { name: 'Soft Candle Light', note: 'Warm flicker grade.' },
    ],
    metrics: [
      { value: 45, suffix: 'min', label: 'Runtime' },
      { value: 22, suffix: 'M', label: 'Frames' },
      { value: 5, label: 'Festivals' },
      { value: 96, suffix: '%', label: 'Critic Score' },
    ],
    timeline: [
      { phase: 'Fold Study', duration: 'Jan 2022', desc: 'Paper simulation tests.' },
      { phase: 'Boards', duration: 'Feb 2022', desc: 'Stop-motion boards.' },
      { phase: 'Build', duration: 'Mar – Jun 2022', desc: '2.5D paper world.' },
      { phase: 'Finish', duration: 'Jul 2022', desc: 'Candle grade.' },
    ],
    challenge:
      'Simulating the charm of physical paper inside a digital pipeline.',
    solution:
      'We shot timing references on a real stop-motion stage, then rebuilt every layer as warped paper in 2.5D.',
    beforeCaption: 'Flat digital art',
    afterCaption: 'Layered paper world',
    gallery: [
      { id: 'pm-1', variant: 1, caption: 'Paper moon' },
      { id: 'pm-2', variant: 3, caption: 'Folded town' },
      { id: 'pm-3', variant: 0, caption: 'Window scene' },
      { id: 'pm-4', variant: 2, caption: 'Candle lit' },
      { id: 'pm-5', variant: 1, caption: 'Goodbye' },
      { id: 'pm-6', variant: 3, caption: 'Cover' },
    ],
    prototype: { type: 'parallax', hint: 'Parallax the paper layers with your cursor.' },
  },
  {
    id: 'void-walker',
    title: 'Void Walker',
    category: 'Game Cinematic',
    year: '2024',
    role: 'Motion · VFX',
    description:
      'A real-time cinematic trailer blending anime silhouette acting with volumetric, rendered depth.',
    theme: '#ff9e00',
    tagline: 'Step beyond the edge.',
    format: 'Trailer · 2 min',
    duration: '1:20',
    liveDemo: 'https://kaze.studio/void-walker',
    github: 'https://github.com/kaze-studio/void-walker',
    techStack: [
      { name: 'Unreal Engine', role: 'Real-time render' },
      { name: 'MetaHuman', role: 'Silhouette acting' },
      { name: 'Niagara', role: 'Volumetric VFX' },
      { name: 'Movie Render', role: 'Final capture' },
    ],
    animationTechniques: [
      { name: 'Silhouette Acting', note: 'Readable shapes in light.' },
      { name: 'Volumetric Fog', note: 'Depth from density.' },
      { name: 'Lens Flare Cut', note: 'Optical transitions.' },
      { name: 'Real-Time DOF', role: 'Cinematic focus' },
    ],
    metrics: [
      { value: 2, suffix: 'min', label: 'Trailer' },
      { value: 60, suffix: 'fps', label: 'Capture' },
      { value: 3, label: 'Trailer Awards' },
      { value: 20, suffix: 'M', label: 'Plays' },
    ],
    timeline: [
      { phase: 'Blockout', duration: 'Nov 2023', desc: 'Camera & beats.' },
      { phase: 'Rig & Act', duration: 'Dec 2023', desc: 'Silhouette performance.' },
      { phase: 'VFX', duration: 'Jan 2024', desc: 'Niagara volumes.' },
      { phase: 'Capture', duration: 'Feb 2024', desc: 'Movie Render master.' },
    ],
    challenge:
      'Keeping anime readability inside physically based, volumetric real-time rendering.',
    solution:
      'We art-directed silhouettes first, then lit for shape — letting fog and flare sell depth without muddying the acting.',
    beforeCaption: 'Flat game render',
    afterCaption: 'Cinematic void',
    gallery: [
      { id: 'vw-1', variant: 0, caption: 'Edge step' },
      { id: 'vw-2', variant: 2, caption: 'Void gate' },
      { id: 'vw-3', variant: 3, caption: 'Flare cut' },
      { id: 'vw-4', variant: 1, caption: 'Walker reveal' },
      { id: 'vw-5', variant: 0, caption: 'Fall' },
      { id: 'vw-6', variant: 2, caption: 'Key art' },
    ],
    prototype: { type: 'character', hint: 'Parallax the void and run the flare sweep.' },
  },
];
